just_student:
    resource: "@JustBundle/Controller/StudentController.php"
    type:     annotation

just_student_type:
    resource: "@JustBundle/Controller/StudentTypeController.php"
    type:     annotation

bunker:
    resource: "@BunkerBundle/Controller/"
    type:     annotation
    prefix:   /

just_chevalier:
    resource: "@JustBundle/Controller/ChevalierController.php"
    type:     annotation

just:
    resource: "@JustBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

